[book]
authors = ["Juraj Lieskovský"]
language = "en"
multilingual = false
src = "src"
title = "Optimal and Predictive Control"

[output.html]
additional-css = ["katex-extra.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[build]
create-missing = false

[preprocessor.katex]
after = ["links"]

[preprocessor.bib]
bibliography = "references.bib"

[preprocessor.mermaid]
command = "mdbook-mermaid"
