[book]
authors = ["Juraj Lieskovský"]
language = "en"
multilingual = false
src = "src"
title = "Optimal and Predictive Control"

[output.html]
additional-css = ["katex-extra.css"]

[build]
create-missing = false

[preprocessor.katex]
after = ["links"]

[preprocessor.bib]
bibliography = "references.bib"
